### PR TITLE
adding autodocumentation for python and C++

### PR DESCRIPTION
**Pull request by timkpaine**
Framework for #384 

Relies on `doxygen` to autogenerate C++ documentation, integrates it with `sphinx` and `sphinx-apidoc` python documentation using `breathe`. Can investigate a tool like [sphinx-js](https://pypi.org/project/sphinx-js/) for hooking in javascript as well. 

# Initial TODOs
- [x] add JSDoc config w/ babel support
- [x] fix sphinx-js bug with sphinx value iteration
- [x] hook in sphinx-js

### CODE REVIEW

**Comment by timkpaine** [comment]
https://github.com/mozilla/sphinx-js/issues/94

**Comment by timkpaine** [comment]
@texodus don't merge this yet

**Comment by timkpaine** [comment]
@texodus good to go, i'll flesh out the rest in a separate PR

**Comment by timkpaine** [comment]
@JHawk @sc1f take a look, and start planning on writing docstrings accordingly

**Comment by texodus** [comment]
Thanks for the PR!

There are already full JSDoc strings for all [public APIs](https://github.com/jpmorganchase/perspective/blob/master/docs/perspective.md).  It would be nice if we could unify the docs across packages to output something consistent - I'd like to not have half of the docs in Github and half in readthedocs if possible.  In the meantime, this is a strict improvement over the 0% python docs we currently publish.

**Pull request merged**
